DROP DATABASE IF EXISTS BOOKNOVA;
CREATE DATABASE BOOKNOVA;
USE BOOKNOVA;


CREATE TABLE RUOLO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RUOLO VARCHAR(50) NOT NULL
);

CREATE TABLE UTENTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_RUOLO INT,
    FOREIGN KEY (ID_RUOLO) REFERENCES RUOLO(ID)
);

CREATE TABLE AUTORE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    BIOGRAFIA TEXT
);

CREATE TABLE EDITORE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE Categoria (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE FORMATO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FORMATO VARCHAR(50) NOT NULL
);

CREATE TABLE CONDIZIONE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIZIONE VARCHAR(100)
);

CREATE TABLE OFFERTA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VALORE DECIMAL(5,2),
    DATA_INIZIO DATE,
    DATA_FINE DATE
);

CREATE TABLE LIBRO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITOLO VARCHAR(200) NOT NULL,
    PREZZO DECIMAL(10,2) NOT NULL,
    DESCRIZIONE TEXT,
    ID_AUTORE INT,
    ID_EDITORE INT,
    ID_CATEGORIA INT,
    ID_FORMATO INT,
    ID_CONDIZIONE INT,
    FOREIGN KEY (ID_AUTORE) REFERENCES Autore(ID),
    FOREIGN KEY (ID_EDITORE) REFERENCES Editore(ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES Categoria(ID),
    FOREIGN KEY (ID_FORMATO) REFERENCES Formato(ID),
    FOREIGN KEY (ID_CONDIZIONE) REFERENCES Condizione(ID)
);

CREATE TABLE LIBRO_OFFERTA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIBRO INT,
    ID_OFFERTA INT,
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID),
    FOREIGN KEY (ID_OFFERTA) REFERENCES OFFERTA(ID)
);

CREATE TABLE WISHLIST (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_INSERIMENTO DATE,
    ID_UTENTE INT,
    ID_LIBRO INT,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID),
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID)
);

CREATE TABLE CARRELLO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT,
    ID_LIBRO INT,
    QUANTITA INT DEFAULT 1,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID),
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID)
);


CREATE TABLE METODO_PAGAMENTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50)
);

CREATE TABLE METODO_SPEDIZIONE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50),
    costo DECIMAL(10,2)
);

CREATE TABLE ORDINE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT,
    ID_METODO_PAGAMENTO INT,
    ID_METODO_SPEDIZIONE INT,
    DATA_ORDINE DATE,
    TOTALE DECIMAL(10,2),
    FOREIGN KEY (ID_UTENTE) REFERENCES Utente(ID),
    FOREIGN KEY (ID_METODO_PAGAMENTO) REFERENCES Metodo_pagamento(ID),
    FOREIGN KEY (ID_METODO_SPEDIZIONE) REFERENCES Metodo_spedizione(ID)
);

CREATE TABLE ORDINE_LIBRO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ORDINE INT,
    ID_LIBRO INT,
    QUANTITA INT,
    PREZZO_UNITARIO DECIMAL(10,2),
    FOREIGN KEY (ID_ORDINE) REFERENCES ORDINE(ID),
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID)
);

CREATE TABLE RECENSIONE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT,
    ID_LIBRO INT,
    TESTO TEXT,
    DATA DATE,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID),
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID)
);

CREATE TABLE VOTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT,
    ID_LIBRO INT,
    VALORE INT,
    DATA DATE,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID),
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID)
);
