DROP DATABASE IF EXISTS BOOKNOVA;
CREATE DATABASE BOOKNOVA;
USE BOOKNOVA;

CREATE TABLE RUOLO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    RUOLO VARCHAR(50) NOT NULL
);

CREATE TABLE UTENTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50) NOT NULL,
    COGNOME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_RUOLO INT,
    INDIRIZZO VARCHAR(255),
    FOREIGN KEY (ID_RUOLO) REFERENCES RUOLO(ID) ON DELETE CASCADE
);

CREATE TABLE AUTORE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    BIOGRAFIA TEXT
);

CREATE TABLE EDITORE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE CATEGORIA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE FORMATO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FORMATO VARCHAR(50) NOT NULL
);

CREATE TABLE CONDIZIONE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIZIONE VARCHAR(100)
);

CREATE TABLE OFFERTA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    VALORE DECIMAL(5,2),
    DATA_INIZIO DATE,
    DATA_FINE DATE
);

CREATE TABLE LIBRO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    TITOLO VARCHAR(200) NOT NULL,
    PREZZO DECIMAL(10,2) NOT NULL,
    DESCRIZIONE TEXT,
    ID_AUTORE INT,
    ID_EDITORE INT,
    ID_CATEGORIA INT,
    ID_FORMATO INT,
    ID_CONDIZIONE INT,
    PAGINE INT,
    ANNO_PUBBLICAZIONE INT,
    IMMAGINE VARCHAR(500),
    FOREIGN KEY (ID_AUTORE) REFERENCES AUTORE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_EDITORE) REFERENCES EDITORE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_FORMATO) REFERENCES FORMATO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_CONDIZIONE) REFERENCES CONDIZIONE(ID) ON DELETE CASCADE
);

CREATE TABLE LIBRO_OFFERTA (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_LIBRO INT,
    ID_OFFERTA INT,
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_OFFERTA) REFERENCES OFFERTA(ID) ON DELETE CASCADE
);

CREATE TABLE WISHLIST (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DATA_INSERIMENTO DATE,
    ID_UTENTE INT,
    ID_LIBRO INT,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID) ON DELETE CASCADE
);

CREATE TABLE CARRELLO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT,
    ID_LIBRO INT,
    QUANTITA INT DEFAULT 1,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID) ON DELETE CASCADE
);

CREATE TABLE METODO_PAGAMENTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(50)
);

CREATE TABLE METODO_SPEDIZIONE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(50),
    costo DECIMAL(10,2)
);

CREATE TABLE ORDINE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT,
    ID_METODO_PAGAMENTO INT,
    ID_METODO_SPEDIZIONE INT,
    DATA_ORDINE DATE,
    TOTALE DECIMAL(10,2),
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_METODO_PAGAMENTO) REFERENCES METODO_PAGAMENTO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_METODO_SPEDIZIONE) REFERENCES METODO_SPEDIZIONE(ID) ON DELETE CASCADE
);

CREATE TABLE ORDINE_OGGETTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_ORDINE INT,
    ID_LIBRO INT,
    QUANTITA INT,
    PREZZO_UNITARIO DECIMAL(10,2),
    FOREIGN KEY (ID_ORDINE) REFERENCES ORDINE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID) ON DELETE CASCADE
);

CREATE TABLE RECENSIONE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT,
    ID_LIBRO INT,
    TESTO TEXT,
    DATA DATE,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID) ON DELETE CASCADE
);

CREATE TABLE VOTO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT,
    ID_LIBRO INT,
    VALORE INT,
    DATA DATE,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_LIBRO) REFERENCES LIBRO(ID) ON DELETE CASCADE
);

CREATE TABLE RECENSIONE_SITO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    ID_UTENTE INT NULL,
    NOME VARCHAR(100) NOT NULL,
    TESTO TEXT NOT NULL,
    DATA DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID) ON DELETE SET NULL
);

CREATE VIEW CART_ITEM AS 
SELECT L.*, C.ID_UTENTE, C.QUANTITA 
FROM LIBRO AS L 
JOIN CARRELLO AS C ON L.ID = C.ID_LIBRO;

-- ============================
-- TABELLE PER 4.3 (PERMESSI)
-- ============================

CREATE TABLE SERVIZIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE UTENTE_RUOLO (
    ID_UTENTE INT,
    ID_RUOLO INT,
    PRIMARY KEY (ID_UTENTE, ID_RUOLO),
    FOREIGN KEY (ID_UTENTE) REFERENCES UTENTE(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_RUOLO) REFERENCES RUOLO(ID) ON DELETE CASCADE
);

CREATE TABLE RUOLO_SERVIZIO (
    ID_RUOLO INT,
    ID_SERVIZIO INT,
    PRIMARY KEY (ID_RUOLO, ID_SERVIZIO),
    FOREIGN KEY (ID_RUOLO) REFERENCES RUOLO(ID) ON DELETE CASCADE,
    FOREIGN KEY (ID_SERVIZIO) REFERENCES SERVIZIO(ID) ON DELETE CASCADE
);
